### ISSUE TITLE
When I run python lstm_classifier.py I get error: No such file or directory: 'embeddings/saved_200d_word_embeddings.pkl

### ISSUE THREAD

**Issue by ZahraAskarzadeh** [Demfier/multimodal-speech-emotion-recognition#20]
Do I need to add some files for word embedding to your code?

**Comment by Demfier** [comment]
Hi @ZahraAskarzadeh 

Sorry for the delayed response.

Can you provide more details about this like your directory structure or files already generated? You are probably missing an `embeddings` folder in the required directory. If not, try deleting the vocab.pkl file, and run the `lstm_classifier.py` again. Ideally, you only need to download the original 6B glove vector file of the required dimension from [here](https://nlp.stanford.edu/projects/glove/), and those embedding files should be created automatically.

**Comment by ZahraAskarzadeh** [comment]
Now it works, thanks

**Comment by Demfier** [comment]
Hi @ZahraAskarzadeh 

Thanks for letting me know. I am closing this issue. Feel free to open up a new one if you hit up on something.

- Gaurav.

**Comment by gy-luck** [comment]
When I run python lstm_classifier.py I get error:  Can't get attribute 'Vocabulary' on <module '__main__' from 'lstm_classifier.py'>
