### ISSUE TITLE
python -c 'import torch; print(torch.cuda.is_available())' is false

### ISSUE THREAD

**Issue by ZahraAskarzadeh** [Demfier/multimodal-speech-emotion-recognition#22]
Hi

torch.cuda.is_available() is false, did you have the same issue?

**Comment by Demfier** [comment]
Hi @ZahraAskarzadeh 

I had run my code on a GPU as training wasn't feasible otherwise. Are you unable to run the code on a CPU?

**Comment by ZahraAskarzadeh** [comment]
Yes, I cannot run it with CPU (it takes forever). Now I'm switching to GPU but after installing drivers still torch.cuda.is_available() is false

**Comment by Demfier** [comment]
Hi @ZahraAskarzadeh 

Sorry for the late reply. If that variable is false, it means that the torch version is not compatible with the CUDA driver on your device. Try looking into it (if you haven't yet)

**Comment by Demfier** [comment]
You can also try using the preprocessed data files here: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0

Hope it helps!
