### ISSUE TITLE
run in 2 hours vs 10

### ISSUE THREAD

**Issue by macgari** [Demfier/multimodal-speech-emotion-recognition#26]
used multiprocessing with 100 processes, 
optimal number may vary based on machine

**Comment by MrCrowbar** [comment]
Cool man!
Could you share how did you arranged the code?
Thanks

**Comment by Demfier** [comment]
You can now access the preprocessed data files here if it helps: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0
