### ISSUE TITLE
No data folder and no dataset available, can someone help ??

### ISSUE THREAD

**Issue by Tushar-R-09** [Demfier/multimodal-speech-emotion-recognition#30]

**Comment by rofe-dl** [comment]
The dataset isn't publicly available. You'll have to request for it from [here](https://sail.usc.edu/iemocap/release_form.php). Make the data folder yourself and put it there.

**Comment by Sowjanya109** [comment]
> The dataset isn't publicly available. You'll have to request for it from [here](https://sail.usc.edu/iemocap/release_form.php). Make the data folder yourself and put it there.

Can please share with us. It's little urgent for my project. I have requested one week before for the dataset but i didn't get any response.

**Comment by Demfier** [comment]
You can access the preprocessed data files here: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0
