### ISSUE TITLE
Questions about document handling.

### ISSUE THREAD

**Issue by chenyu-l** [Demfier/multimodal-speech-emotion-recognition#31]
I want to know what changes have been made to the two CSV files（audio_test.csv、audio_train.csv ）（in data/s2e/） to generate modified_ df_ test. csv、modified_ df_ train. csv ？
Because I met a mistake using 'torch.LongTensor(data[1])' directly for the original two CSV files when run lstm_classfier.py . And you didn't tell us how to generate the two new CSV file.

**Comment by Demfier** [comment]
The modified version oversamples data points for surprise and fear (as they are underrepresented). A 90/10 train/test split is then created.

**Comment by llitmus** [comment]
I was faced with the same problem as chenyu-I, and I did the split, and got modified_ df_ test. csv、modified_ df_ train. csv. but there's another problem: too many dimensions 'str' when running the lstm_classifier.

**Comment by Demfier** [comment]
@llitmus could you paste the full error log? It's difficult to for me to assist otherwise.

**Comment by llitmus** [comment]
This is my error
when running the lstm_classifier. Something wrong in utils.py. Maybe I did the split false.

ValueError                                Traceback (most recent call last)
~/multimodal-speech-emotion-recognition-master/lstm_classifier/s2e/lstm_classifier.py in <module>
     49     optimizer = optim.Adam(model.parameters(), lr=config['learning_rate'])
     50 
---> 51     train_batches = load_data()
     52     test_pairs = load_data(test=True)
     53 

~/multimodal-speech-emotion-recognition-master/lstm_classifier/s2e/utils.py in load_data(batched, test, file_dir)
     28             output_batch.append(e[1])
     29         batches.append([torch.FloatTensor(input_batch),
---> 30                         torch.LongTensor(output_batch)])
     31     return batches
     32 

**ValueError: too many dimensions 'str'**

```
This is my split code. I add it in the 4th .ipynb
modified_df_train,modified_df_test = train_test_split(df, test_size=0.10)
modified_df_train.to_csv('../data/s2e/modified_df_train.csv', index=False)
modified_df_test.to_csv('../data/s2e/modified_df_test.csv', index=False)

print(modified_df_train.shape, modified_df_test.shape)
```

the output is alright .
`(1913, 10) (213, 10)`

And I'm trying to use **data/s2e/audio_train.csv** in the lstm_classifier but failed either

Thank u so much!

**Comment by llitmus** [comment]
@Demfier I sovled the problem! just delete the 'wav_file' col of the modified_df_train and that  works!^-^ Anyway, thank u so much!

**Comment by llitmus** [comment]
Oh! I just sovled the problem by droping the col 'wav_file' .hhh.
But there's a loss of  predit_proba.py .hhh in s2e. I copied the combined predit py ^-^
Anyway,thanks a lot!

**Comment by raniaahmed123** [comment]
@llitmus  could you please help me how did you solve the problem?
i have same issue?
did you create modified data frames for train and test from modified_df.csv file ?
or you used audio_train.csv and audio_test.csv instead of modified dataframe?

**Comment by yyh565655555** [comment]
> Oh! I just sovled the problem by droping the col 'wav_file' .hhh. But there's a loss of predit_proba.py .hhh in s2e. I copied the combined predit py ^-^ Anyway,thanks a lot!

sorry to bother you, i also meet the same problem, would you mind sharing your csv files?

**Comment by Demfier** [comment]
Hi,

You can access the preprocessed data files here: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0

Hope this helps!

**Comment by yyh565655555** [comment]
thank u very much，this helps me a lot

---- Replied Message ----
From Gaurav ***@***.***> Date 10/27/2023 11:14 To Demfier/multimodal-speech-emotion-recognition ***@***.***> Cc ***@***.***>,
Comment ***@***.***> Subject Re: [Demfier/multimodal-speech-emotion-recognition] Questions about document handling. (Issue #31)  

Hi,
You can access the preprocessed data files here: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0
Hope this helps!
