### ISSUE TITLE
Weights of the pre-trained models

### ISSUE THREAD

**Issue by m2moiz** [Demfier/multimodal-speech-emotion-recognition#34]
Could you provide the weights of the pretrained models (MLP and the LSTM)

**Comment by She-yh** [comment]
> Could you provide the weights of the pretrained models (MLP and the LSTM)

@m2moiz 
Hi, did you get the weights file? It's not easy for me to apply the datasets

**Comment by Demfier** [comment]
You can train your models on the preprocessed data here: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0
