### ISSUE TITLE
about the modified_df_train.csv

### ISSUE THREAD

**Issue by yyh565655555** [Demfier/multimodal-speech-emotion-recognition#37]
FileNotFoundError: [Errno 2] No such file or directory: '../../data/s2e/modified_df_train.csv', i dont know how to produce this csv, shall someone send to 1215544940@qq.com if it can not be public

**Comment by yyh565655555** [comment]
and combined csv also not found

**Comment by cuiyimeng** [comment]
Hello, have you obtained this file?

**Comment by yyh565655555** [comment]
@Demfier

**Comment by Demfier** [comment]
Hi all, sorry for the delayed response. You can get the modified_df_train.csv file by splitting the modified_df.csv file you get after running 4_prepared_data.ipynb notebook. I've also prepared a folder with the processed files: https://www.dropbox.com/scl/fo/jdzz2y9nngw9rxsbz9vyj/h?rlkey=bji7zcqclusagzfwa7alm59hx&dl=0
